name: Rocket.Chat Desktop App Release Action
description: Releases the Rocket.Chat Desktop app

inputs:
  ref:
    description: 'Forced ref to override github.context.payload.ref'
    required: false
  repository_owner:
    description: 'Owner of the repository where the release will be made'
    required: false
  repository_name:
    description: 'Name of the repository where the release will be made'
    required: false
  mac_csc_link:
    description: 'The base64-encoded data of certificates (*.p12) for code signing for macOS'
    required: true
  mac_csc_key_password:
    description: 'The password to decrypt the certificates for code signing for macOS'
    required: true
  mac_apple_id:
    description: 'The Apple ID for notarization'
    required: true
  mac_apple_id_password:
    description: 'The password associated to Apple ID for notarization'
    required: true
  mac_asc_provider:
    description: 'The membership account associated with the Apple Developer account'
    required: true
  win_kms_key_resource:
    description: 'Google Cloud KMS key resource (projects/.../locations/.../keyRings/.../cryptoKeys/.../cryptoKeyVersions/N)'
    required: true
  win_kms_cert_sha1:
    description: 'SHA1 thumbprint of the issued code signing certificate in Windows cert store (optional if win_cert_path provided)'
    required: false
  win_kms_csp:
    description: 'CSP name (default: Google Cloud KMS Provider)'
    required: false
  win_timestamp_url:
    description: 'RFC3161 timestamp URL (default: http://timestamp.digicert.com)'
    required: false
  win_cert_path:
    description: 'Path to issued code signing certificate (user.crt) to install in CI runner (optional)'
    required: false
  win_intermediate_path:
    description: 'Path to intermediate CA certificate to install in CI runner (optional)'
    required: false
  win_root_path:
    description: 'Path to root CA certificate to install in CI runner (optional)'
    required: false
  github_token:
    description: 'The GitHub token to publish releases'
    required: true
  snapcraft_token:
    description: 'The Snapcraft token to publish releases'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
