'use strict';

const gulp = require('gulp');
const jetpack = require('fs-jetpack');
const bundle = require('./bundle');
const istanbul = require('rollup-plugin-istanbul');

const createEntryFile = (srcDir, matching, outputDir, entryFileName, rollupOptions) => {
    return srcDir.findAsync('.', { matching })
        .then(specPaths => specPaths.map(path => `import './${ path.replace(/\\/g, '/') }';`))
        .then(imports => (
            "// This file is generated automatically.\n" +
            "// All modifications will be lost.\n" +
            imports.join('\n')
        ))
        .then(entryFileContent => srcDir.writeAsync(entryFileName, entryFileContent))
        .then(() => bundle(srcDir.path(entryFileName), outputDir.path(entryFileName), rollupOptions))
        .then(() => srcDir.remove(entryFileName));
};

gulp.task('build-unit-tests', [ 'environment' ], () => {
    return createEntryFile(jetpack.cwd('src'), '*.spec.js', jetpack.cwd('app'), 'specs.js.autogenerated', {
        rollupPlugins: [
            istanbul({
                exclude: ['**/*.spec.js', '**/specs.js.autogenerated'],
                sourcemap: true
            })
        ]
    });
});

gulp.task('build-e2e-tests', [ 'build-app' ], () => {
    return createEntryFile(jetpack.cwd('e2e'), '*.e2e.js', jetpack.cwd('app'), 'e2e.js.autogenerated');
});
