import type { PersistableValues } from '../common/types/PersistableValues';

export const extractPersistableValues = ({
  currentView,
  doCheckForUpdatesOnStartup,
  downloads,
  externalProtocols,
  isEachUpdatesSettingConfigurable,
  isFlashWindowEnabled,
  isMenuBarEnabled,
  isShowWindowOnUnreadChangedEnabled,
  isSideBarEnabled,
  isTrayIconEnabled,
  isUpdatingEnabled,
  rootWindowState,
  servers,
  skippedUpdateVersion,
  trustedCertificates,
}: PersistableValues): PersistableValues => ({
  currentView,
  doCheckForUpdatesOnStartup,
  downloads,
  externalProtocols,
  isEachUpdatesSettingConfigurable,
  isFlashWindowEnabled,
  isMenuBarEnabled,
  isShowWindowOnUnreadChangedEnabled,
  isSideBarEnabled,
  isTrayIconEnabled,
  isUpdatingEnabled,
  rootWindowState,
  servers,
  skippedUpdateVersion,
  trustedCertificates,
});
