import {
	ABOUT_DIALOG_DISMISSED,
	MENU_BAR_ABOUT_CLICKED,
	SCREEN_SHARING_DIALOG_DISMISSED,
	SCREEN_SHARING_DIALOG_SOURCE_SELECTED,
	UPDATE_DIALOG_DISMISSED,
	UPDATES_NEW_VERSION_AVAILABLE,
	WEBVIEW_SCREEN_SHARING_SOURCE_REQUESTED,
} from '../actions';

export const openDialog = (state = null, { type }) => {
	switch (type) {
		case MENU_BAR_ABOUT_CLICKED:
			return 'about';

		case WEBVIEW_SCREEN_SHARING_SOURCE_REQUESTED:
			return 'screen-sharing';

		case UPDATES_NEW_VERSION_AVAILABLE:
			return 'update';

		case ABOUT_DIALOG_DISMISSED:
		case SCREEN_SHARING_DIALOG_DISMISSED:
		case SCREEN_SHARING_DIALOG_SOURCE_SELECTED:
		case UPDATE_DIALOG_DISMISSED:
			return null;
	}

	return state;
};
