name: rocketchat-desktop
version: 2.13.0-develop
summary: Rocket.Chat
description: Rocket.Chat Native Cross-Platform Desktop Application via Electron.
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  rocketchat-desktop:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/rocketchat-desktop
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      - camera
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    organize:
      rocketchat: rocketchat-desktop
    source: dist/linux-unpacked
    after:
      - desktop-glib-only
