name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: RocketChat.RocketChat
          version: ${{ github.event.release.tag_name }}
          installers-regex: '.(exe|msi)$'
          token: ${{ secrets.WINGET_TOKEN }}
